networks:
  academynet:
    driver: bridge

services:
  mysqldb:
    container_name: db_container
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: academy_db
      MYSQL_ROOT_PASSWORD: 123456
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3407:3306"
    networks:
      - academynet

  app:
    container_name: app_container
    build: .
    ports:
      - 3002:3000
    depends_on:
      - mysqldb
    restart: unless-stopped
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: academy_db
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 10
      SERVER_PORT: 3000
    networks:
      - academynet
volumes:
  db: